# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    steps:
      - run: git clone https://github.com/ZhengSherpas/nestjs-rest-sample.git

    steps:
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
